-- Seed exercises table with predefined exercises
-- This migration inserts all the predefined exercises into the database

INSERT INTO exercises (id, name, category, muscle_group) VALUES
  -- Chest
  ('bench-press', 'Bench Press', 'Chest', 'Upper Body'),
  ('incline-bench-press', 'Incline Bench Press', 'Chest', 'Upper Body'),
  ('decline-bench-press', 'Decline Bench Press', 'Chest', 'Upper Body'),
  ('dumbbell-press', 'Dumbbell Press', 'Chest', 'Upper Body'),
  ('chest-fly', 'Chest Fly', 'Chest', 'Upper Body'),
  ('push-ups', 'Push-ups', 'Chest', 'Upper Body'),
  ('cable-crossover-high', 'Cable Crossover (High)', 'Chest', 'Upper Body'),
  ('cable-crossover-low', 'Cable Crossover (Low)', 'Chest', 'Upper Body'),
  ('cable-crossover-mid', 'Cable Crossover (Mid)', 'Chest', 'Upper Body'),
  ('pec-deck-fly', 'Pec Deck Fly', 'Chest', 'Upper Body'),
  ('chest-dips', 'Chest Dips', 'Chest', 'Upper Body'),
  ('incline-dumbbell-fly', 'Incline Dumbbell Fly', 'Chest', 'Upper Body'),
  ('decline-dumbbell-fly', 'Decline Dumbbell Fly', 'Chest', 'Upper Body'),
  ('wide-grip-bench-press', 'Wide Grip Bench Press', 'Chest', 'Upper Body'),
  ('narrow-grip-bench-press', 'Narrow Grip Bench Press', 'Chest', 'Upper Body'),
  ('diamond-push-ups', 'Diamond Push-ups', 'Chest', 'Upper Body'),
  ('wide-push-ups', 'Wide Push-ups', 'Chest', 'Upper Body'),
  ('decline-push-ups', 'Decline Push-ups', 'Chest', 'Upper Body'),
  ('incline-push-ups', 'Incline Push-ups', 'Chest', 'Upper Body'),
  ('cable-fly', 'Cable Fly', 'Chest', 'Upper Body'),
  
  -- Back
  ('deadlift', 'Deadlift', 'Back', 'Upper Body'),
  ('barbell-row', 'Barbell Row', 'Back', 'Upper Body'),
  ('pull-ups', 'Pull-ups', 'Back', 'Upper Body'),
  ('lat-pulldown', 'Lat Pulldown', 'Back', 'Upper Body'),
  ('t-bar-row', 'T-Bar Row', 'Back', 'Upper Body'),
  ('cable-row', 'Cable Row', 'Back', 'Upper Body'),
  ('one-arm-dumbbell-row', 'One-Arm Dumbbell Row', 'Back', 'Upper Body'),
  ('face-pull', 'Face Pull', 'Back', 'Upper Body'),
  ('reverse-fly', 'Reverse Fly', 'Back', 'Upper Body'),
  ('wide-grip-pull-up', 'Wide Grip Pull-up', 'Back', 'Upper Body'),
  ('close-grip-pull-up', 'Close Grip Pull-up', 'Back', 'Upper Body'),
  ('chin-up', 'Chin-up', 'Back', 'Upper Body'),
  ('seated-cable-row', 'Seated Cable Row', 'Back', 'Upper Body'),
  ('wide-grip-lat-pulldown', 'Wide Grip Lat Pulldown', 'Back', 'Upper Body'),
  ('close-grip-lat-pulldown', 'Close Grip Lat Pulldown', 'Back', 'Upper Body'),
  ('bent-over-row', 'Bent-Over Row', 'Back', 'Upper Body'),
  ('wide-grip-bent-over-row', 'Wide Grip Bent-Over Row', 'Back', 'Upper Body'),
  ('underhand-bent-over-row', 'Underhand Bent-Over Row', 'Back', 'Upper Body'),
  ('shrugs', 'Shrugs', 'Back', 'Upper Body'),
  
  -- Shoulders
  ('overhead-press', 'Overhead Press', 'Shoulders', 'Upper Body'),
  ('dumbbell-shoulder-press', 'Dumbbell Shoulder Press', 'Shoulders', 'Upper Body'),
  ('lateral-raise', 'Lateral Raise', 'Shoulders', 'Upper Body'),
  ('front-raise', 'Front Raise', 'Shoulders', 'Upper Body'),
  ('rear-delt-fly', 'Rear Delt Fly', 'Shoulders', 'Upper Body'),
  ('upright-row', 'Upright Row', 'Shoulders', 'Upper Body'),
  ('arnold-press', 'Arnold Press', 'Shoulders', 'Upper Body'),
  ('pike-push-up', 'Pike Push-up', 'Shoulders', 'Upper Body'),
  ('cable-lateral-raise', 'Cable Lateral Raise', 'Shoulders', 'Upper Body'),
  ('cable-front-raise', 'Cable Front Raise', 'Shoulders', 'Upper Body'),
  ('reverse-cable-fly', 'Reverse Cable Fly', 'Shoulders', 'Upper Body'),
  ('behind-the-neck-press', 'Behind-the-Neck Press', 'Shoulders', 'Upper Body'),
  ('landmine-press', 'Landmine Press', 'Shoulders', 'Upper Body'),
  ('handstand-push-up', 'Handstand Push-up', 'Shoulders', 'Upper Body'),
  ('band-pull-apart', 'Band Pull-Apart', 'Shoulders', 'Upper Body'),
  
  -- Arms
  ('barbell-curl', 'Barbell Curl', 'Arms', 'Upper Body'),
  ('dumbbell-curl', 'Dumbbell Curl', 'Arms', 'Upper Body'),
  ('hammer-curl', 'Hammer Curl', 'Arms', 'Upper Body'),
  ('tricep-dips', 'Tricep Dips', 'Arms', 'Upper Body'),
  ('tricep-pushdown', 'Tricep Pushdown', 'Arms', 'Upper Body'),
  ('close-grip-bench-press', 'Close-Grip Bench Press', 'Arms', 'Upper Body'),
  ('preacher-curl', 'Preacher Curl', 'Arms', 'Upper Body'),
  ('cable-curl', 'Cable Curl', 'Arms', 'Upper Body'),
  ('concentration-curl', 'Concentration Curl', 'Arms', 'Upper Body'),
  ('reverse-curl', 'Reverse Curl', 'Arms', 'Upper Body'),
  ('cable-tricep-extension', 'Cable Tricep Extension', 'Arms', 'Upper Body'),
  ('overhead-tricep-extension', 'Overhead Tricep Extension', 'Arms', 'Upper Body'),
  ('skull-crushers', 'Skull Crushers', 'Arms', 'Upper Body'),
  ('tricep-kickback', 'Tricep Kickback', 'Arms', 'Upper Body'),
  ('rope-pushdown', 'Rope Pushdown', 'Arms', 'Upper Body'),
  
  -- Legs
  ('squat', 'Squat', 'Legs', 'Lower Body'),
  ('leg-press', 'Leg Press', 'Legs', 'Lower Body'),
  ('leg-extension', 'Leg Extension', 'Legs', 'Lower Body'),
  ('leg-curl', 'Leg Curl', 'Legs', 'Lower Body'),
  ('lunges', 'Lunges', 'Legs', 'Lower Body'),
  ('romanian-deadlift', 'Romanian Deadlift', 'Legs', 'Lower Body'),
  ('calf-raise', 'Calf Raise', 'Legs', 'Lower Body'),
  ('bulgarian-split-squat', 'Bulgarian Split Squat', 'Legs', 'Lower Body'),
  ('front-squat', 'Front Squat', 'Legs', 'Lower Body'),
  ('hack-squat', 'Hack Squat', 'Legs', 'Lower Body'),
  ('goblet-squat', 'Goblet Squat', 'Legs', 'Lower Body'),
  ('sumo-squat', 'Sumo Squat', 'Legs', 'Lower Body'),
  ('walking-lunges', 'Walking Lunges', 'Legs', 'Lower Body'),
  ('reverse-lunges', 'Reverse Lunges', 'Legs', 'Lower Body'),
  ('lateral-lunges', 'Lateral Lunges', 'Legs', 'Lower Body'),
  ('step-ups', 'Step-ups', 'Legs', 'Lower Body'),
  ('leg-press-wide', 'Leg Press (Wide Stance)', 'Legs', 'Lower Body'),
  ('leg-press-narrow', 'Leg Press (Narrow Stance)', 'Legs', 'Lower Body'),
  ('single-leg-deadlift', 'Single Leg Deadlift', 'Legs', 'Lower Body'),
  ('good-mornings', 'Good Mornings', 'Legs', 'Lower Body'),
  ('hip-thrust', 'Hip Thrust', 'Legs', 'Lower Body'),
  ('glute-bridge', 'Glute Bridge', 'Legs', 'Lower Body'),
  ('wall-sit', 'Wall Sit', 'Legs', 'Lower Body'),
  
  -- Core
  ('plank', 'Plank', 'Core', 'Core'),
  ('crunches', 'Crunches', 'Core', 'Core'),
  ('sit-ups', 'Sit-ups', 'Core', 'Core'),
  ('russian-twist', 'Russian Twist', 'Core', 'Core'),
  ('leg-raises', 'Leg Raises', 'Core', 'Core'),
  ('mountain-climbers', 'Mountain Climbers', 'Core', 'Core'),
  ('dead-bug', 'Dead Bug', 'Core', 'Core'),
  ('bird-dog', 'Bird Dog', 'Core', 'Core'),
  ('hollow-body-hold', 'Hollow Body Hold', 'Core', 'Core'),
  ('v-ups', 'V-Ups', 'Core', 'Core'),
  ('bicycle-crunches', 'Bicycle Crunches', 'Core', 'Core'),
  ('side-plank', 'Side Plank', 'Core', 'Core'),
  ('reverse-crunch', 'Reverse Crunch', 'Core', 'Core'),
  ('ab-wheel-rollout', 'Ab Wheel Rollout', 'Core', 'Core'),
  ('hanging-leg-raise', 'Hanging Leg Raise', 'Core', 'Core'),
  ('l-sit', 'L-Sit', 'Core', 'Core')
ON CONFLICT (id) DO NOTHING;
